### ISSUE TITLE
not a issue but i added drawing with local as image host provider

### ISSUE THREAD

**Issue by kamilthecitratester** [PF2M/Indigo#8]
heres how to do it: step 1: add /images to the repo, thats it

**Comment by ariankordi** [comment]
thanks for testing indigo! it seems like this isn't specific to drawings and is just basically "uploads of any sort don't work until you do this"
it was kind of an oversight to have the local image provider exist, have it work, and have it be the default and to set the images endpoint to /images, all while not actually creating an images folder. WHOOOOOOOOOOOPS!!!

this will be fixed in a later commit, i guess either indigo can create the directory if it doesn't exist on startup or we can just make it in the repo but i will plan it

**Comment by ariankordi** [comment]
The latest commit 525499ba5b151b9aeed2d53d03aea31e6c241f6e SHOULD fix this, as in, it should automatically create the images folder for you.
Try running Indigo again - start fresh, pull the latest version, and see if it lets you upload images without having to make that directory (it should do it itself). Let me know how it goes!

**Comment by kamilthecitratester** [comment]
ok, i will do that now.

**Comment by kamilthecitratester** [comment]
ok, it works perfectly and u have to change Local (not yet implemented) to Local, cuz its in indigo now

**Comment by ariankordi** [comment]
whoops yeah that's something that we should get around to, as well as actually letting you change the directory from /images to whatever else you want.. the local image provider was also implemented separately for banama.club, so i will think about this and consider just importing that version which seems to be a little more complete, when it comes time to merge other changes from banama.club
the local image provider in there currently is just something hacked up by me for some smf9 clone lmao

**Comment by kamilthecitratester** [comment]
i never used google+ and i dont know anybody that uses banama.club, sorry

**Comment by kamilthecitratester** [comment]
i opened a issue in https://github.com/ariankordi/closedverse aka closedverse main repo
